import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdir, readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { chromium } from "@playwright/test";

const root = process.cwd();
const dist = join(root, "apps/fluent-preview/dist");
const mime = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".svg": "image/svg+xml" };
const server = createServer(async (request, response) => {
  const pathname = request.url === "/" ? "/index.html" : new URL(request.url, "http://test").pathname;
  const path = normalize(join(dist, pathname));
  if (!path.startsWith(dist)) return response.writeHead(403).end();
  try { response.setHeader("content-type", mime[extname(path)] ?? "application/octet-stream"); response.end(await readFile(path)); }
  catch { response.writeHead(404).end(); }
});
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const { port } = server.address();
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE, headless: true });
const artifact = join(root, "test/artifacts");
await mkdir(artifact, { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: "light", reducedMotion: "no-preference" });
  await page.goto(`http://127.0.0.1:${port}`, { waitUntil: "networkidle" });
  for (const name of ["button-primary", "toggle-button", "switch", "fluent-slider", "fluent-select", "menu-trigger", "file-picker", "scroll-viewer", "dialog-trigger", "popover-trigger", "theme-mode", "accent-select", "details"]) assert.equal(await page.getByTestId(name).count(), 1, `missing ${name}`);
  for (const type of ["text", "search", "email", "url", "tel", "password", "number", "color", "date", "time", "datetime-local", "month", "week"]) assert.ok(await page.locator(`input[type="${type}"]`).count() >= 1, `missing native ${type}`);
  assert.equal(await page.locator(".fluent-file-picker").count(), 1);
  assert.equal(await page.locator(".fluent-file-picker__input").isVisible(), false);
  assert.equal(await page.locator(".fluent-notice").count(), 4);
  assert.equal(await page.locator(".fluent-progress-bar").count(), 4);
  assert.equal(await page.locator(".fluent-progress-bar--with-indicator").count(), 2);
  assert.equal(await page.locator(".fluent-progress-bar--snap").count(), 1);
  assert.equal(await page.locator(".fluent-progress-bar__indicator").first().textContent(), "62%");
  assert.equal(await page.locator(".fluent-progress-bar--snap .fluent-progress-bar__indicator").textContent(), "60%");
  assert.equal(await page.locator(".fluent-progress-bar--snap .fluent-progress-bar__tick").count(), 11);
  assert.equal(await page.locator(".fluent-progress-ring").count(), 2);
  assert.equal(await page.locator(".fluent-navigation").count(), 1);
  assert.equal(await page.locator("#choices").getByRole("checkbox").count(), 3);
  assert.equal(await page.getByRole("checkbox", { name: "Partially selected" }).evaluate(node => node.indeterminate), true);
  const radioLayout = await page.locator(".fluent-radio").first().evaluate(node => { const input = node.querySelector("input").getBoundingClientRect(); const label = node.querySelector("span").getBoundingClientRect(); return Math.abs((input.top + input.height / 2) - (label.top + label.height / 2)); });
  assert.ok(radioLayout < 3, "radio label is not aligned beside its control");
  const resolveThemeColor = async (name) => page.locator(".catalog-theme").evaluate((node, variable) => {
    const probe = document.createElement("span");
    probe.style.backgroundColor = getComputedStyle(node).getPropertyValue(variable).trim();
    node.append(probe);
    const color = getComputedStyle(probe).backgroundColor;
    probe.remove();
    return color;
  }, name);
  const controlHover = await resolveThemeColor("--fluent-control-hover");
  const accentHover = await resolveThemeColor("--fluent-accent-hover");
  const waitForHover = () => page.waitForTimeout(180);
  const background = (locator) => locator.evaluate(node => getComputedStyle(node).backgroundColor);
  const transform = (locator) => locator.evaluate(node => getComputedStyle(node).transform);
  const secondary = page.getByRole("button", { name: "Secondary", exact: true });
  const secondaryRest = await background(secondary);
  await secondary.hover(); await waitForHover();
  assert.equal(await background(secondary), controlHover, "secondary button does not use the reference hover surface");
  assert.notEqual(await background(secondary), secondaryRest, "secondary button hover has no visual state");
  assert.equal(await transform(secondary), "none", "button hover changed its geometry");
  const invalid = page.locator("#native input[aria-invalid=true]");
  assert.notEqual(await invalid.evaluate(node => getComputedStyle(node).borderTopColor), await page.locator("#native input[type=text]").first().evaluate(node => getComputedStyle(node).borderTopColor), "native invalid state is not visible");
  const primary = page.getByTestId("button-primary");
  const restColor = await primary.evaluate(node => getComputedStyle(node).backgroundColor);
  await primary.hover();
  await page.waitForTimeout(220);
  const hoverColor = await primary.evaluate(node => getComputedStyle(node).backgroundColor);
  assert.notEqual(hoverColor, restColor, "primary hover has no visual state");
  await page.mouse.down();
  await page.waitForTimeout(220);
  assert.notEqual(await primary.evaluate(node => getComputedStyle(node).backgroundColor), hoverColor, "primary pressed has no visual state");
  assert.equal(await transform(primary), "none", "button pressed changed its geometry");
  await page.mouse.up();
  const toggle = page.getByTestId("toggle-button");
  await toggle.click();
  assert.equal(await toggle.getAttribute("aria-pressed"), "true");
  await toggle.hover(); await waitForHover();
  assert.notEqual(await background(toggle), controlHover, "selected toggle lost its selected surface on hover");
  assert.equal(await transform(toggle), "none", "selected toggle hover changed its geometry");
  const checkedBox = page.locator(".fluent-checkbox").filter({ hasText: "Remember choice" });
  const checkedBoxInput = checkedBox.locator(".fluent-checkbox__input");
  await checkedBox.hover(); await waitForHover();
  assert.equal(await checkedBoxInput.isChecked(), true);
  assert.equal(await background(checkedBoxInput), accentHover, "checked checkbox hover lost its checked accent");
  assert.equal(await transform(checkedBoxInput), "none", "checkbox hover changed its geometry");
  const partialBox = page.locator(".fluent-checkbox").filter({ hasText: "Partially selected" });
  const partialBoxInput = partialBox.locator(".fluent-checkbox__input");
  await partialBox.hover(); await waitForHover();
  assert.equal(await partialBoxInput.evaluate(node => node.indeterminate), true);
  assert.equal(await background(partialBoxInput), accentHover, "indeterminate checkbox hover lost its state accent");
  const comfortableRadio = page.locator(".fluent-radio").filter({ hasText: "Comfortable" });
  const compactRadio = page.locator(".fluent-radio").filter({ hasText: "Compact" });
  await comfortableRadio.hover(); await waitForHover();
  const uncheckedRadioHover = await background(comfortableRadio.locator(".fluent-radio__input"));
  await compactRadio.hover(); await waitForHover();
  assert.notEqual(await background(compactRadio.locator(".fluent-radio__input")), uncheckedRadioHover, "checked radio hover looks like an unchecked radio");
  const switchControl = page.getByTestId("switch");
  const switchThumb = switchControl.locator(".fluent-switch__thumb");
  const switchThumbRest = await transform(switchThumb);
  await switchControl.hover(); await waitForHover();
  assert.equal(await background(switchControl.locator(".fluent-switch__track")), accentHover, "checked switch hover lost its checked accent");
  assert.equal(await transform(switchThumb), switchThumbRest, "switch hover changed the thumb geometry");
  const sliderInput = page.getByTestId("fluent-slider");
  await sliderInput.hover(); await waitForHover();
  assert.equal(await sliderInput.evaluate(node => getComputedStyle(node, "::-webkit-slider-thumb").transform), "none", "slider hover changed the thumb geometry");
  const fieldInput = page.locator(".fluent-field__input:not(:disabled):not([readonly]):not([data-invalid])").first();
  const fieldRest = await background(fieldInput);
  await fieldInput.hover(); await waitForHover();
  assert.equal(await background(fieldInput), controlHover, "field hover does not use the reference hover surface");
  assert.notEqual(await background(fieldInput), fieldRest, "field hover has no visual state");
  const selectedNav = page.locator(".fluent-navigation__item.is-selected");
  const selectedNavRest = await background(selectedNav);
  await selectedNav.hover(); await waitForHover();
  assert.equal(await background(selectedNav), selectedNavRest, "selected navigation item was overwritten by hover");
  assert.equal(await page.locator(".fluent-navigation__selection").count(), 0, "navigation still has an independent cover layer");
  await page.getByTestId("theme-mode").focus();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Tab");
  await selectedNav.hover();
  assert.equal(await selectedNav.evaluate(node => getComputedStyle(node).outlineStyle), "solid", "navigation focus is hidden by hover");
  await page.getByTestId("button-primary").focus();
  await page.keyboard.press("Tab");
  await page.keyboard.press("Shift+Tab");
  assert.equal(await primary.evaluate(node => getComputedStyle(node).outlineStyle), "solid", "keyboard focus is not visible");
  await page.getByTestId("switch").click();
  assert.equal(await page.getByTestId("switch").getAttribute("aria-checked"), "false");
  const pickerInput = page.locator(".fluent-file-picker__input");
  await pickerInput.setInputFiles([{ name: "notes.md", mimeType: "text/markdown", buffer: Buffer.from("notes") }]);
  assert.equal(await page.locator(".fluent-file-picker__file").textContent(), "notes.md");
  assert.equal(await page.getByRole("button", { name: "Disabled" }).isDisabled(), true);
  await page.getByTestId("fluent-select").click();
  assert.equal(await page.getByRole("listbox").count(), 1);
  assert.equal(await page.getByRole("option", { name: "Unavailable" }).isDisabled(), true);
  await page.keyboard.press("Escape");
  await page.getByTestId("menu-trigger").click();
  assert.equal(await page.getByRole("menu").count(), 1);
  assert.equal(await page.getByRole("separator").count(), 1);
  const selectedMenuItem = page.getByRole("menuitemcheckbox", { name: "Copy" });
  const selectedMenuRest = await background(selectedMenuItem);
  await selectedMenuItem.hover(); await waitForHover();
  assert.equal(await background(selectedMenuItem), selectedMenuRest, "selected menu item was overwritten by hover");
  assert.notEqual(await background(selectedMenuItem), controlHover, "selected menu item looks like an unselected item");
  await page.getByRole("menuitemcheckbox", { name: "Pin" }).click();
  assert.equal(await page.getByRole("menuitemcheckbox", { name: "Pin" }).getAttribute("aria-checked"), "true");
  assert.equal(await page.getByRole("menuitemcheckbox", { name: "Delete" }).isDisabled(), true);
  await page.keyboard.press("Escape");
  await page.getByTestId("details").click();
  assert.equal(await page.getByTestId("details").evaluate((node) => node.open), true);
  const selectedRow = page.locator("tr[aria-selected=true]");
  const selectedRowRest = await background(selectedRow);
  await selectedRow.hover(); await waitForHover();
  assert.equal(await background(selectedRow), selectedRowRest, "selected native row was overwritten by hover");
  await page.getByTestId("popover-trigger").click();
  assert.equal(await page.getByText("This is a real FluentPopover.").count(), 1);
  await page.keyboard.press("Escape");
  await page.getByTestId("dialog-trigger").click();
  assert.equal(await page.getByRole("dialog", { name: "Catalog dialog" }).count(), 1);
  await page.keyboard.press("Escape");
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.getByTestId("theme-mode").click();
  await page.getByRole("option", { name: "Light", exact: true }).click();
  await page.screenshot({ path: join(artifact, "fluent-catalog-light.png"), fullPage: true });
  await page.getByTestId("theme-mode").click();
  await page.getByRole("option", { name: "Dark", exact: true }).click();
  assert.equal(await page.locator(".catalog-theme").getAttribute("data-fluent-theme"), "dark");
  await page.screenshot({ path: join(artifact, "fluent-catalog-dark.png"), fullPage: true });
  const forced = await browser.newPage({ viewport: { width: 1280, height: 900 }, forcedColors: "active" });
  await forced.goto(`http://127.0.0.1:${port}`); await forced.screenshot({ path: join(artifact, "fluent-catalog-forced-colors.png"), fullPage: true }); await forced.close();
  const reduced = await browser.newPage({ viewport: { width: 1280, height: 900 }, reducedMotion: "reduce" });
  await reduced.goto(`http://127.0.0.1:${port}`); assert.equal(await reduced.emulateMedia({ reducedMotion: "reduce" }), undefined); await reduced.screenshot({ path: join(artifact, "fluent-catalog-reduced-motion.png"), fullPage: true }); await reduced.close();
  console.log("Fluent catalog browser coverage passed: 12 catalog entry points, 14 native input types, four preference screenshots");
} finally { await browser.close(); await new Promise((resolve) => server.close(resolve)); }
