import { FluentButton, FluentCheckbox, FluentDialog, FluentField, FluentMenu, FluentNavigation, FluentNotice, FluentNumberField, FluentPasswordField, FluentPopover, FluentProgressBar, FluentProgressRing, FluentRadio, FluentScrollViewer, FluentSelect, FluentSlider, FluentSwitch, FluentTextArea, FluentTheme, FluentToggleButton } from "@platform-kit/fluent/vue";
import "@platform-kit/fluent/style.css";
import { createApp, defineComponent, h, ref, type ComponentPublicInstance } from "vue";
import "./preview.css";

type ThemeMode = "light" | "dark" | "system";
const accents = ["#0067c0", "#8e4585", "#107c10", "#ca5010"];
const options = [{ value: "alpha", label: "Alpha" }, { value: "beta", label: "Beta" }, { value: "locked", label: "Unavailable", disabled: true }];
const menuItems = [{ value: "copy", label: "Copy" }, { separator: true }, { value: "pin", label: "Pin" }, { value: "delete", label: "Delete", disabled: true }];

const Catalog = defineComponent({
  setup() {
    const theme = ref<ThemeMode>("system"), accent = ref(accents[0]), toggle = ref(false), switched = ref(true), checked = ref(true), radio = ref("compact"), text = ref("Sample text"), number = ref<number | null>(42), range = ref(55), selected = ref("alpha"), menuOpen = ref(false), menuValues = ref<string[]>(["copy"]), dialogOpen = ref(false), popoverOpen = ref(false), activeNav = ref("catalog");
    const menuAnchor = ref<HTMLElement | null>(null), popoverAnchor = ref<HTMLElement | null>(null);
    const card = (id: string, title: string, children: any[]) => h("section", { class: "catalog-card", id, "aria-labelledby": `${id}-title` }, [h("h2", { id: `${id}-title` }, title), ...children]);
    const native = (label: string, type: string, props: Record<string, unknown> = {}) => h("label", { class: "native-field" }, [h("span", label), h("input", { type, ...props })]);
    const anchor = (target: typeof menuAnchor | typeof popoverAnchor) => (element: Element | ComponentPublicInstance | null) => target.value = element instanceof HTMLElement ? element : null;
    return () => h(FluentTheme, { mode: theme.value, accent: accent.value, class: "catalog-theme" }, { default: () => h("div", { class: "catalog-page" }, [
      h("header", { class: "catalog-header" }, [h("div", [h("p", { class: "catalog-kicker" }, "@platform-kit/fluent 0.2.0"), h("h1", "Fluent control catalog")]), h("div", { class: "catalog-settings", "aria-label": "Catalog settings" }, [
        h(FluentSelect, { label: "Theme", "data-testid": "theme-mode", modelValue: theme.value, options: [{ value: "light", label: "Light" }, { value: "dark", label: "Dark" }, { value: "system", label: "System" }], "onUpdate:modelValue": (value: string) => theme.value = value as ThemeMode }),
        h(FluentSelect, { label: "Accent", "data-testid": "accent-select", modelValue: accent.value, options: accents.map(value => ({ value, label: value })), "onUpdate:modelValue": (value: string) => accent.value = value })
      ])]),
      h("div", { class: "catalog-layout" }, [h("aside", { class: "catalog-sidebar" }, [h(FluentNavigation, { label: "Catalog sections", modelValue: activeNav.value, items: [{ key: "catalog", label: "Controls" }, { key: "native", label: "Native inputs" }, { key: "semantic", label: "Semantic HTML" }, { key: "overlays", label: "Overlays" }], "onUpdate:modelValue": (v: string) => activeNav.value = v, onSelect: (v: string) => document.getElementById(v)?.scrollIntoView({ behavior: "smooth" }) }), h("p", "Every card uses package CSS or semantic native elements.")]),
        h("main", { class: "catalog-main" }, [
          h("section", { class: "catalog-intro", id: "catalog" }, [h("h2", "Component exports"), h("p", "Each existing Vue export is interactive. Browser coverage checks default, hover, pressed, disabled, focus, checked, expanded, and system preference states.")]),
          h("div", { class: "catalog-grid" }, [
            card("buttons", "Buttons and toggle", [h("div", { class: "control-row" }, [h(FluentButton, { tone: "primary", "data-testid": "button-primary" }, () => "Primary"), h(FluentButton, { tone: "secondary" }, () => "Secondary"), h(FluentButton, { tone: "danger" }, () => "Danger"), h(FluentButton, { tone: "subtle" }, () => "Subtle"), h(FluentButton, { iconOnly: true, "aria-label": "Add item" }, () => "+")]), h("div", { class: "control-row" }, [h(FluentToggleButton, { modelValue: toggle.value, "data-testid": "toggle-button", "onUpdate:modelValue": (v: boolean) => toggle.value = v }, () => toggle.value ? "Pinned" : "Pin"), h(FluentButton, { busy: true, "aria-label": "Saving" }, () => "Saving"), h(FluentButton, { disabled: true }, () => "Disabled")])]),
            card("choices", "Switch, checkbox, radio and slider", [h(FluentSwitch, { modelValue: switched.value, label: "Notifications", "data-testid": "switch", "onUpdate:modelValue": (v: boolean) => switched.value = v }), h(FluentSwitch, { modelValue: false, label: "Disabled switch", disabled: true }), h(FluentCheckbox, { modelValue: checked.value, label: "Remember choice", "onUpdate:modelValue": (v: boolean) => checked.value = v }), h(FluentCheckbox, { modelValue: false, label: "Disabled checkbox", disabled: true }), h("div", { class: "control-row" }, [h(FluentRadio, { modelValue: radio.value, value: "compact", label: "Compact", "onUpdate:modelValue": (v: string) => radio.value = v }), h(FluentRadio, { modelValue: radio.value, value: "comfortable", label: "Comfortable", "onUpdate:modelValue": (v: string) => radio.value = v }), h(FluentRadio, { modelValue: radio.value, value: "locked", label: "Disabled", disabled: true })]), h(FluentSlider, { modelValue: range.value, min: 0, max: 100, label: "Volume", "data-testid": "fluent-slider", "onUpdate:modelValue": (v: number) => range.value = v })]),
            card("fields", "Fluent fields", [h(FluentField, { modelValue: text.value, label: "Text field", placeholder: "Type here", "onUpdate:modelValue": (v: string) => text.value = v }), h(FluentField, { modelValue: "read only", label: "Read-only field", readonly: true }), h(FluentField, { modelValue: "invalid", label: "Invalid field", invalid: true }), h(FluentField, { modelValue: "disabled", label: "Disabled field", disabled: true }), h(FluentPasswordField, { modelValue: "secret", label: "Password" }), h(FluentNumberField, { modelValue: number.value, label: "Number", "onUpdate:modelValue": (v: number | null) => number.value = v }), h(FluentTextArea, { modelValue: "A multiline value.", label: "Textarea" })]),
            card("selection", "Select and menu", [h(FluentSelect, { modelValue: selected.value, label: "Fluent select", options, "data-testid": "fluent-select", "onUpdate:modelValue": (v: string) => selected.value = v }), h("span", { ref: anchor(menuAnchor) }, [h(FluentButton, { "data-testid": "menu-trigger", onClick: () => menuOpen.value = !menuOpen.value }, () => "Open multi-select menu")]), h(FluentMenu, { open: menuOpen.value, label: "Actions", anchor: menuAnchor.value, items: menuItems, multiple: true, modelValue: menuValues.value, closeOnSelect: false, "onUpdate:open": (v: boolean) => menuOpen.value = v, "onUpdate:modelValue": (v: string[]) => menuValues.value = v })]),
            card("feedback", "Notice, progress and scroll viewer", [h(FluentNotice, { tone: "info" }, () => "Informational notice"), h(FluentNotice, { tone: "success" }, () => "Saved successfully"), h(FluentNotice, { tone: "warning" }, () => "Needs review"), h(FluentNotice, { tone: "danger" }, () => "An error occurred"), h("div", { class: "progress-row" }, [h(FluentProgressBar, { value: 62, label: "62 percent" }), h(FluentProgressBar, { indeterminate: true, label: "Loading" }), h(FluentProgressRing, { value: 62, indeterminate: false, label: "62 percent" }), h(FluentProgressRing, { indeterminate: true, label: "Loading" })]), h(FluentScrollViewer, { "data-testid": "scroll-viewer" }, () => h("div", { class: "scroll-sample" }, "Scrollable FluentScrollViewer content. ".repeat(30)))])
          ]),
          h("section", { class: "catalog-section", id: "native" }, [h("h2", "Native input types"), h("div", { class: "native-grid" }, [native("Text", "text", { value: "Text" }), native("Search", "search", { value: "Search" }), native("Email", "email", { value: "name@example.com" }), native("URL", "url", { value: "https://example.com" }), native("Telephone", "tel", { value: "+1 555 0100" }), native("Password", "password", { value: "password" }), native("Number", "number", { value: 7 }), native("File", "file"), native("Color", "color", { value: "#0067c0" }), native("Date", "date"), native("Time", "time"), native("Date and time", "datetime-local"), native("Month", "month"), native("Week", "week"), native("Disabled", "text", { disabled: true, value: "Disabled" }), native("Read-only", "text", { readOnly: true, value: "Read-only" }), native("Invalid", "email", { required: true, value: "invalid", "aria-invalid": "true" })])]),
          h("section", { class: "catalog-section", id: "semantic" }, [h("h2", "Semantic controls"), h("div", { class: "semantic-grid" }, [h("fieldset", [h("legend", "Native choice controls"), h("label", [h("input", { type: "checkbox", checked: true }), " Native checkbox"]), h("label", [h("input", { type: "radio", name: "native-radio", checked: true }), " Native radio"]), h("label", [h("input", { type: "range", value: 45 }), " Native range"])]), h("div", [h("a", { href: "#semantic" }, "Standard link"), " · ", h("a", { href: "#semantic", "aria-disabled": "true", onClick: (e: Event) => e.preventDefault() }, "Disabled link")]), h("details", { "data-testid": "details" }, [h("summary", "Expandable summary"), h("p", "Details content is visible when expanded.")]), h("table", [h("caption", "Styled table"), h("thead", [h("tr", [h("th", "Name"), h("th", "Status")])]), h("tbody", [h("tr", { "aria-selected": "true" }, [h("td", "Selected row"), h("td", "Ready")]), h("tr", [h("td", "Hover row"), h("td", "Waiting")])])])])]),
          h("section", { class: "catalog-section", id: "overlays" }, [h("h2", "Dialog and popover"), h("div", { class: "control-row" }, [h(FluentButton, { "data-testid": "dialog-trigger", onClick: () => dialogOpen.value = true }, () => "Open dialog"), h("span", { ref: anchor(popoverAnchor) }, [h(FluentButton, { "data-testid": "popover-trigger", onClick: () => popoverOpen.value = !popoverOpen.value }, () => "Open popover")])])]),
          h("section", { class: "catalog-section catalog-limitations" }, [h("h2", "Catalog boundaries"), h("p", "Every current Vue export and all native controls styled by style.css are represented. DataGrid, TreeView, DatePicker, CommandBar, TeachingTip, SplitView, Tabs, and InfoBar are not package exports and are intentionally not simulated.")])
        ])
      ]),
      h(FluentPopover, { open: popoverOpen.value, label: "Catalog popover", anchor: popoverAnchor.value, "onUpdate:open": (v: boolean) => popoverOpen.value = v }, { default: () => h("p", "This is a real FluentPopover.") }), h(FluentDialog, { open: dialogOpen.value, label: "Catalog dialog", "onUpdate:open": (v: boolean) => dialogOpen.value = v }, { default: () => h("p", "This is a real FluentDialog. Escape closes it."), footer: () => h(FluentButton, { onClick: () => dialogOpen.value = false }, () => "Close") })
    ]) });
  }
});
createApp(Catalog).mount("#app");
