import ollamaMark from "./assets/ollama.svg?raw";

const files = import.meta.glob(
  [
    "../node_modules/@lobehub/icons-static-svg/icons/alibaba-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/azure-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/bedrock-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/cerebras-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/claude-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/cloudflare-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/codebuddy-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/codex-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/cohere-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/deepseek-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/fireworks-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/gemini-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/githubcopilot.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/grok.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/groq.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/huggingface-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/kimi-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/meta-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/minimax-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/mistral-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/moonshot.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/nvidia-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/openai.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/opencode.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/openrouter-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/perplexity-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/siliconcloud-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/stepfun-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/tencent-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/together-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/trae-color.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/vercel.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/xai.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/zai.svg",
    "../node_modules/@lobehub/icons-static-svg/icons/zhipu-color.svg",
  ],
  { query: "?raw", import: "default", eager: true },
) as Record<string, string>;

const ICON_FILES: Record<string, string> = {
  "anthropic": "claude-color",
  "openai": "openai",
  "openai-codex": "codex-color",
  "github-copilot": "githubcopilot",
  "google": "gemini-color",
  "gemini": "gemini-color",
  "deepseek": "deepseek-color",
  "grok": "grok",
  "xai": "xai",
  "kimi": "kimi-color",
  "kimi-coding": "kimi-color",
  "kimi-for-coding": "kimi-color",
  "moonshotai": "moonshot",
  "opencode": "opencode",
  "opencode-go": "opencode",
  "openrouter": "openrouter-color",
  "zhipuai": "zhipu-color",
  "zai": "zai",
  "tencent-tokenhub": "tencent-color",
  "workbuddy": "codebuddy-color",
  "trae": "trae-color",
  "traecode": "trae-color",
  "meta": "meta-color",
  "mistral": "mistral-color",
  "groq": "groq",
  "cohere": "cohere-color",
  "perplexity": "perplexity-color",
  "alibaba": "alibaba-color",
  "minimax": "minimax-color",
  "nvidia": "nvidia-color",
  "huggingface": "huggingface-color",
  "azure": "azure-color",
  "together": "together-color",
  "fireworks": "fireworks-color",
  "cerebras": "cerebras-color",
  "amazon-bedrock": "bedrock-color",
  "vercel": "vercel",
  "cloudflare-workers-ai": "cloudflare-color",
  "stepfun": "stepfun-color",
  "siliconflow": "siliconcloud-color",
};

const LOCAL_ICONS: Record<string, string> = { "ollama": ollamaMark, "ollama-cloud": ollamaMark };

export function builtinProviderIcon(id: string): string | null {
  const key = id.trim().toLowerCase();
  if (Object.hasOwn(LOCAL_ICONS, key)) return LOCAL_ICONS[key]!;
  const file = ICON_FILES[key];
  return file ? files[`../node_modules/@lobehub/icons-static-svg/icons/${file}.svg`] ?? null : null;
}
